# Generated by Django 5.2.5 on 2025-08-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("helpline_number", models.CharField(blank=True, max_length=30)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("vaccination", "Vaccination"),
                            ("checkup", "Health Checkup"),
                            ("awareness", "Awareness"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-date", "-created_at"],},
        ),
    ]
