# Generated by Django 5.2.5 on 2025-08-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_medicine_vaccine"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign", name="maps_url", field=models.URLField(blank=True),
        ),
    ]
