# Generated by Django 5.2.5 on 2025-08-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0003_campaign_maps_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="medicines",
            field=models.ManyToManyField(
                blank=True, related_name="campaigns", to="campaigns.medicine"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="vaccines",
            field=models.ManyToManyField(
                blank=True, related_name="campaigns", to="campaigns.vaccine"
            ),
        ),
    ]
