# Generated by Django 5.2.5 on 2025-08-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_campaign_medicines_campaign_vaccines"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="age_group",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="medicine",
            name="type",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
