# Generated by Django 5.2.5 on 2025-08-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="maps_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
